name = "ScaledNumbersOutput"
uuid = "782ee38f-53f4-49ed-a0ae-b2a4e296146b"
authors = ["Glen Hertz <glen.hertz@gmail.com>"]
version = "1.0.2"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
OrderedCollections = "1"
julia = "1.6, 1.7, 1.8, 1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
