name = "ScaledNumbersOutput"
uuid = "782ee38f-53f4-49ed-a0ae-b2a4e296146b"
authors = ["Glen Hertz <glen.hertz@gmail.com>"]
version = "1.0.1"

[compat]
julia = "1.6, 1.7, 1.8, 1.9"
OrderedCollections = "1"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]